[package]
name = "cfdg"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[lib]
name = "cfdg"
path = "src/lib.rs"

[[bin]]
name = "cfdgd"
path = "src/main.rs"

[dependencies]
serde = "0.8.2"
serde_json = "0.8.1"
serde_macros = "0.8.2"
clap = "2.10.0"
